
exports.up = function(knex, Promise) {
  return Promise.all([
    knex.schema.table('workpacks', function (table) {
      table.string('t_type', 32)
      table.float('t_duration_estimate')
      table.float('t_p_effort_hours')
      table.float('t_p_resource_quantity')
      table.float('t_p_percentage_avaiable')
      table.float('t_p_performance_factor')
      table.float('t_a_previous_activity')
      table.float('t_a_previous_duration')
      table.float('t_a_current_activity')
      table.float('t_a_multiplier')
      table.string('t_a_previous_activity_txt', 512)
      table.string('t_a_previous_duration_txt', 512)
      table.string('t_a_current_activity_txt', 512)
      table.string('t_a_multiplier_txt', 512)
      table.float('t_3_optimistic_duration')
      table.float('t_3_mostlikely_duration')
      table.float('t_3_pessimistic_duration')
      table.string('t_3_wheighting_equation', 512)
      table.string('c_type', 32)
      table.float('c_cost_estimate')
      table.string('c_p_variable_cost', 512)
      table.float('c_p_cost_per_unit')
      table.float('c_p_number_of_units')
      table.float('c_a_previous_activity')
      table.string('c_a_previous_activity_txt', 512)
      table.float('c_a_previous_cost')
      table.float('c_a_current_activity')
      table.string('c_a_current_activity_txt', 512)
      table.float('c_a_multiplier')
      table.float('c_3_optimistic_cost')
      table.float('c_3_mostlikely_cost')
      table.float('c_3_pessimistic_cost')
      table.string('c_3_wheighting_equation', 512)
    })
  ])
}

exports.down = function(knex, Promise) {
  return Promise.all([
    knex.schema.table('workpacks', function (table) {
      table.dropColumn('t_type')
      table.dropColumn('c_type')
      table.dropColumn('t_duration_estimate')
      table.dropColumn('t_p_effort_hours')
      table.dropColumn('t_p_resource_quantity')
      table.dropColumn('t_p_percentage_avaiable')
      table.dropColumn('t_p_performance_factor')
      table.dropColumn('t_a_previous_activity')
      table.dropColumn('t_a_previous_duration')
      table.dropColumn('t_a_current_activity')
      table.dropColumn('t_a_multiplier')
      table.dropColumn('t_a_previous_activity_txt')
      table.dropColumn('t_a_previous_duration_txt')
      table.dropColumn('t_a_current_activity_txt')
      table.dropColumn('t_a_multiplier_txt')
      table.dropColumn('t_3_optimistic_duration')
      table.dropColumn('t_3_mostlikely_duration')
      table.dropColumn('t_3_pessimistic_duration')
      table.dropColumn('t_3_wheighting_equation')
      table.dropColumn('c_cost_estimate')
      table.dropColumn('c_p_variable_cost')
      table.dropColumn('c_p_cost_per_unit')
      table.dropColumn('c_p_number_of_units')
      table.dropColumn('c_a_previous_activity')
      table.dropColumn('c_a_previous_activity_txt')
      table.dropColumn('c_a_previous_cost')
      table.dropColumn('c_a_current_activity')
      table.dropColumn('c_a_current_activity_txt')
      table.dropColumn('c_a_multiplier')
      table.dropColumn('c_3_optimistic_cost')
      table.dropColumn('c_3_mostlikely_cost')
      table.dropColumn('c_3_pessimistic_cost')
      table.dropColumn('c_3_wheighting_equation')
    })
  ])
}
